#---
#mermaid: true
#---


# Basic options
title: Giordano_Bruno
name: My Site

# Build settings
markdown: kramdown
theme: minima

#plugins:
#  - jekyll-spaceship

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
